corpid:
  yinian: wwb1241eeac52c8c3e

secret:
  contact: acXBLGT4cNPcm0jIfNPtleWhR6Gz-Jym9B99do8NOwQ

dev:
  BASE_URL: https://qyapi.weixin.qq.com/cgi-bin/
prod:
  BASE_URL: https://qyapi.weixin.qq.com/cgi-bin/P